name: Workflow
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!master'
jobs:
  build:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Nuke Build
        run: ./build.cmd --GitHubToken ${{ secrets.GITHUB_TOKEN }}